const assert = require('node:assert/strict');
const { mkdir } = require('node:fs/promises');
const { resolve } = require('node:path');
const { pathToFileURL } = require('node:url');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const { createApp } = await import(pathToFileURL(resolve(__dirname, '../server.mjs')).href);
  const app = createApp({ dbPath: ':memory:', mode: 'demo', enableScheduler: false });
  await app.ready;
  await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${app.server.address().port}`;
  const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) }).catch(async error => { await app.close(); throw error; });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const state = async () => (await page.request.get(url + '/api/state')).json();
  const action = async locator => {
    const result = page.waitForResponse(response => response.url() === url + '/api/actions');
    await locator.click();
    const response = await result;
    assert.equal(response.status(), 200, await response.text());
    await page.waitForFunction(() => !document.querySelector('#toast')?.classList.contains('error'));
    return response.json();
  };
  try {
    await page.goto(url);
    await page.locator('[data-command=demo-staff]').click();
    await page.getByRole('heading', { name: 'Good care, kept on track.' }).waitFor();
    await mkdir('docs/screenshots', { recursive: true });
    await page.screenshot({ path: 'docs/screenshots/overview.png', fullPage: true });
    const patientPage = await browser.newPage({ viewport: { width: 1440, height: 1050 } });
    patientPage.on('pageerror', error => errors.push(error.message));
    await patientPage.goto(url + '/?view=patient');
    await patientPage.locator('[name=name]').waitFor();
    await patientPage.screenshot({ path: 'docs/screenshots/pre-arrival.png', fullPage: true });
    const intake = patientPage.locator('[data-form=pre_arrival]');
    await intake.locator('[name=name]').fill('Kiran Demo');
    await intake.locator('[name=language]').selectOption('Hindi');
    await intake.locator('[name=departmentId]').selectOption('endocrinology');
    await intake.locator('[name=contactConsent]').check();
    await intake.locator('[name=scheduleConsent]').check();
    const intakeResponse = patientPage.waitForResponse(response => response.url().endsWith('/api/session/patient'));
    await intake.locator('button[type=submit]').click();
    const createdResponse = await intakeResponse;
    assert.equal(createdResponse.status(), 200);
    const created = await createdResponse.json();
    const patientId = created.result.patientId;
    const initialId = created.result.episodeId;
    await patientPage.getByRole('heading', { name: 'Kiran Demo', exact: true }).waitFor();
    await page.reload();
    await page.locator(`[data-patient="${patientId}"]`).first().click();
    let current;
    await page.getByRole('heading', { name: 'Kiran Demo', exact: true }).waitFor();
    assert.equal(created.result.status, 'department_inquiry');
    await page.screenshot({ path: 'docs/screenshots/routing.png', fullPage: true });
    current = await action(page.locator(`[data-accept="${initialId}"]`).first());
    assert.equal(current.episodes.find(e => e.id === initialId).status, 'booked');
    await patientPage.locator('[data-command=refresh]').click();
    await patientPage.getByRole('heading', { name: 'Your appointment is ready' }).first().waitFor();
    const beforeArrival = await (await patientPage.request.get(url + '/api/state')).json();
    assert.equal(beforeArrival.patients.length, 1);
    assert.equal(beforeArrival.patients[0].id, patientId);
    assert.equal(beforeArrival.episodes[0].checkedInAt, null);
    assert.equal(beforeArrival.episodes[0].completedAt, null);
    assert.equal(beforeArrival.audit, undefined);
    await patientPage.screenshot({ path: 'docs/screenshots/patient-plan.png', fullPage: true });
    const upload = patientPage.locator('[data-form=upload_document]');
    await upload.locator('[name=file]').setInputFiles(resolve(__dirname, '../docs/demo-files/referral-demo.txt'));
    const uploaded = patientPage.waitForResponse(response => response.url() === url + '/api/documents');
    await upload.getByRole('button', { name: 'Save document' }).click();
    assert.equal((await uploaded).status(), 201);
    await patientPage.getByText('referral-demo.txt', { exact: true }).waitFor();
    await page.reload();
    await page.locator('nav [data-nav="journeys"]').click();
    await page.locator(`[data-patient="${patientId}"]`).first().click();
    await page.getByText('referral-demo.txt', { exact: true }).waitFor();
    await patientPage.setViewportSize({ width: 390, height: 844 });
    assert.ok(await patientPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));

    for (const id of ['referral', 'reports', 'appointment']) await action(page.locator(`[data-document="${id}"]`));
    await action(page.getByRole('button', { name: 'Record check-in', exact: true }));
    const complete = page.locator('form[data-form="complete_visit"]');
    await complete.locator('[name="followUpDate"]').fill('2026-10-06');
    await complete.locator('[name="evidence"]').fill('Synthetic front-desk register entry QA-01.');
    current = await action(complete.getByRole('button', { name: /Confirm visit complete/ }));
    const followId = current.result.episodeId;
    assert.notEqual(followId, initialId);
    await page.locator('.episode-tab.active').getByText('Follow-up 1', { exact: true }).waitFor();
    await page.locator('[data-command="demo-tools"]').click();
    await page.locator('#demo-date').fill('2026-10-07');
    await action(page.locator('[data-command="set-date"]'));
    await page.locator('nav [data-nav="inbox"]').click();
    current = await action(page.getByRole('button', { name: 'Run reminders', exact: true }));
    assert.ok(current.messages.some(m => m.episodeId === followId && m.kind === 'reminder'));
    const reply = page.locator('form[data-form="patient_reply"]');
    await reply.locator('[name="barrier"]').selectOption('travel');
    await reply.locator('[name="text"]').fill('I could not arrange transport.');
    current = await action(reply.getByRole('button', { name: 'Add simulated patient reply' }));
    await action(page.locator('[data-enhance]').first());
    await page.screenshot({ path: 'docs/screenshots/follow-up.png', fullPage: true });
    current = await action(page.locator('[data-approve]').first());
    assert.notEqual(current.episodes.find(e => e.id === followId).status, 'completed');
    const resolutionForm = page.locator('form[data-form="resolve_barrier"]');
    await resolutionForm.locator('[name="note"]').fill('Patient confirmed a workable appointment day after speaking with the desk.');
    await action(resolutionForm.getByRole('button', { name: 'Log resolution' }));
    await page.locator('nav [data-nav="journeys"]').click();
    current = await action(page.locator(`[data-accept="${followId}"]`).first());
    assert.equal(current.episodes.find(e => e.id === followId).originalDueDate, '2026-10-06');
    await action(page.getByRole('button', { name: 'Record check-in', exact: true }));
    const returnVisit = page.locator('form[data-form="complete_visit"]');
    await returnVisit.locator('[name="evidence"]').fill('Synthetic return visit register entry QA-02.');
    current = await action(returnVisit.getByRole('button', { name: /Confirm visit complete/ }));
    assert.equal(current.episodes.find(e => e.id === followId).status, 'completed');
    await page.reload();
    await page.getByRole('heading', { name: 'Good care, kept on track.' }).waitFor();
    assert.ok((await state()).patients.some(p => p.id === patientId));
    await page.setViewportSize({ width: 390, height: 844 });
    await mkdir('test-results', { recursive: true });
    await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'Mobile overflow');
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ passed: true, browserErrors: errors, route: 'home enquiry -> automatic department inbox -> one acceptance -> assigned doctor and slot -> encrypted upload -> checklist -> attendance -> follow-up -> reminder -> barrier -> approved reply -> automatic follow-up booking -> confirmed return', responsiveWidth: 390, patientId, followId }, null, 2));
  } finally {
    await browser.close();
    await app.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
